import { COMPONENT_NAME, COMPONENT_NAME_ACTION, COMPONENT_NAME_TITLE } from "@/components/FILE_NAME"

export function COMPONENT_NAME_VIEW() {
  return (
    <COMPONENT_NAME>
      <COMPONENT_NAME_TITLE>COMPONENT_NAME Title</COMPONENT_NAME_TITLE>
      <COMPONENT_NAME_ACTION>COMPONENT_NAME Action</COMPONENT_NAME_ACTION>
    </COMPONENT_NAME>
  )
}
