import type { ComponentGroup } from './types'

// This file is auto-generated by scripts/pb.workspace/generate-component-hierarchy.mjs.
// Do not edit manually.
export const componentHierarchy: ComponentGroup[] = [
  {
    "name": "Card",
    "children": [
      "CardHeader",
      "CardFooter",
      "CardTitle",
      "CardAction",
      "CardDescription",
      "CardContent"
    ]
  },
  {
    "name": "Frame",
    "children": [
      "FrameTitle",
      "FrameAction"
    ]
  }
]
